services:
  lightdash:
    image: lightdash/lightdash:latest
    environment:
      PGHOST: ep-autumn-sea-aeyv34za-pooler.c-2.us-east-2.aws.neon.tech
      PGPORT: 5432
      PGDATABASE: neondb
      PGUSER: neondb_owner
      PGPASSWORD: npg_0ECLzgxKnsi5
      PGSSLMODE: require
      LIGHTDASH_SECRET: supersecretkey123
      LIGHTDASH_PORT: 8080
      SITE_URL: http://0.0.0.0:8080
      LIGHTDASH_PROJECTS_DIR: /dbt
    ports:
      - "8080:8080"
    volumes:
      - /home/itadmin/my_dbt_project:/dbt
      - /home/itadmin/.dbt:/root/.dbt
    restart: unless-stopped
