services:
  lightdash:
    image: lightdash/lightdash:latest
    environment:
      DATABASE_HOST: ep-frosty-shadow-aexobfx1-pooler.c-2.us-east-2.aws.neon.tech
      DATABASE_PORT: 5432
      DATABASE_NAME: lightdash           # Change if your DB name is different
      DATABASE_USERNAME: neondb
      DATABASE_PASSWORD: Phen0mSauce19002!
      LIGHTDASH_SECRET: supersecretkey123
      LIGHTDASH_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
